"use client";
import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, CheckCircle2, Clock3, MapPin, PawPrint, RotateCcw, Search } from "lucide-react";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

const examples = [
  { id: "RQP-001", animal: "Dog", title: "Injured dog near the market", location: "Mathura · Market Road", urgency: "High", status: "Reported", description: "A community dog needs assessment after a road accident. A location and photo accompany the report." },
  { id: "RQP-002", animal: "Cat", title: "Kitten stranded on a rooftop", location: "Mathura · Residential Lane", urgency: "Medium", status: "Assigned", description: "A kitten is stranded on a roof. A responder is coordinating safe access with the property owner." },
  { id: "RQP-003", animal: "Bird", title: "Bird unable to fly", location: "Mathura · Community Park", urgency: "Medium", status: "Rescued", description: "A bird was reported near a walking path and has been transferred for professional assessment." },
  { id: "RQP-004", animal: "Cow", title: "Animal needs a welfare check", location: "Mathura · Station Road", urgency: "Low", status: "Reported", description: "A resident has requested a welfare check. The report is waiting for responder review." },
];
const stages = ["Reported", "Assigned", "Rescued", "Closed"];

export default function DemoPage() {
  const [cases, setCases] = useState(examples);
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("All");
  const [selected, setSelected] = useState(examples[0].id);
  const visible = useMemo(() => cases.filter(c => (filter === "All" || c.status === filter) && `${c.id} ${c.animal} ${c.title} ${c.location}`.toLowerCase().includes(query.toLowerCase())), [cases, query, filter]);
  const active = cases.find(c => c.id === selected)!;
  const finished = cases.filter(c => ["Rescued", "Closed"].includes(c.status)).length;
  const advance = () => setCases(previous => previous.map(c => c.id === selected ? { ...c, status: stages[Math.min(stages.indexOf(c.status) + 1, 3)] } : c));
  return <><Navbar /><main className="container py-12 md:py-16 space-y-8">
    <div className="rounded-xl border border-primary/20 bg-primary/5 px-4 py-3 text-sm"><strong>Interactive demo.</strong> Fictional cases, local session only. No report is sent and no responder is alerted.</div>
    <div className="flex flex-wrap justify-between items-end gap-6"><div><p className="text-primary text-sm font-semibold uppercase tracking-widest">A little care. A clear next step.</p><h1 className="font-display text-4xl md:text-6xl font-bold tracking-tight mt-3">Every rescue starts<br />with someone noticing.</h1><p className="mt-4 text-muted-foreground max-w-xl">Explore how a report becomes a coordinated case. Search the queue, open a case, and move it through the rescue timeline.</p></div><button className="inline-flex items-center gap-2 rounded-full border px-4 py-2 text-sm hover:bg-muted" onClick={() => {setCases(examples); setQuery(""); setFilter("All"); setSelected(examples[0].id);}}><RotateCcw size={16} />Reset demo</button></div>
    <div className="grid sm:grid-cols-3 gap-4">{[{label:"Sample reports", value:cases.length, icon:PawPrint},{label:"Awaiting follow-up",value:cases.length-finished,icon:Clock3},{label:"Rescued or closed",value:finished,icon:CheckCircle2}].map(({label,value,icon:Icon}) => <div key={label} className="rounded-2xl border bg-card p-6 flex justify-between items-center"><div><p className="text-sm text-muted-foreground">{label}</p><p className="text-4xl font-bold mt-2 tabular-nums" aria-live="polite">{value}</p></div><Icon className="text-primary" size={28} /></div>)}</div>
    <div className="grid lg:grid-cols-[1.15fr_1fr] gap-6 items-start"><section className="rounded-2xl border bg-card p-5 space-y-5" aria-label="Sample rescue queue"><div className="flex justify-between"><h2 className="text-xl font-bold">Rescue queue</h2><span className="text-sm text-muted-foreground">{visible.length} cases</span></div><label className="flex gap-2 items-center border rounded-xl px-3"><Search size={18} className="text-muted-foreground" /><span className="sr-only">Search sample cases</span><input className="w-full py-3 bg-transparent outline-none" placeholder="Search animal, case ID, or location" value={query} onChange={e=>setQuery(e.target.value)} /></label><div className="flex flex-wrap gap-2" aria-label="Filter by status">{["All",...stages].map(s=><button key={s} aria-pressed={s===filter} onClick={()=>setFilter(s)} className={`text-xs rounded-full px-3 py-2 border ${s===filter?"bg-primary text-primary-foreground border-primary":"hover:bg-muted"}`}>{s}</button>)}</div><div className="space-y-3">{visible.length===0 && <p className="py-8 text-center text-muted-foreground">No cases match. Try another search or status.</p>}{visible.map(c=><button key={c.id} onClick={()=>setSelected(c.id)} aria-pressed={selected===c.id} className={`w-full text-left rounded-xl border p-4 transition ${selected===c.id?"border-primary bg-primary/5":"hover:bg-muted"}`}><div className="flex justify-between gap-2"><span className="text-xs text-muted-foreground">{c.id} · {c.animal}</span><span className={`text-xs font-semibold ${c.urgency==="High"?"text-red-600":"text-muted-foreground"}`}>{c.urgency} priority</span></div><h3 className="font-semibold mt-2">{c.title}</h3><div className="flex flex-wrap justify-between gap-2 mt-3 text-xs text-muted-foreground"><span className="inline-flex gap-1 items-center"><MapPin size={12}/>{c.location}</span><span>{c.status}</span></div></button>)}</div></section>
    <section className="rounded-2xl border bg-card overflow-hidden" aria-label="Selected case"><div className="bg-gradient-to-br from-primary/15 to-amber-100/40 dark:to-amber-950/30 p-7"><span className="text-xs uppercase tracking-wider text-primary font-semibold">Case workspace · {active.id}</span><h2 className="text-2xl font-bold mt-3">{active.title}</h2><p className="text-sm text-muted-foreground mt-3">{active.description}</p></div><div className="p-7"><h3 className="font-semibold">Rescue timeline</h3><ol className="mt-5 space-y-5">{stages.map((stage,i)=><li key={stage} className="flex items-center gap-3"><span className={`h-8 w-8 rounded-full grid place-items-center text-sm ${i<=stages.indexOf(active.status)?"bg-primary text-primary-foreground":"bg-muted text-muted-foreground"}`}>{i<stages.indexOf(active.status)?<CheckCircle2 size={16}/>:i+1}</span><span className="text-sm">{stage}{stage===active.status && <span className="ml-2 text-xs text-primary">Current</span>}</span></li>)}</ol><button disabled={active.status==="Closed"} onClick={advance} className="mt-7 w-full rounded-xl bg-primary text-primary-foreground py-3 text-sm font-semibold disabled:opacity-50 inline-flex items-center justify-center gap-2">{active.status==="Closed"?"Case complete":`Simulate: ${stages[stages.indexOf(active.status)+1]}`}<ArrowRight size={16}/></button><p className="text-xs text-muted-foreground mt-3">Status changes here demonstrate the intended workflow. Production NGO and admin actions still need backend endpoints.</p></div></section></div>
    <div className="rounded-2xl border p-6 flex flex-wrap justify-between items-center gap-4"><div><h2 className="font-bold">Ready to explore the full implementation?</h2><p className="text-sm text-muted-foreground mt-1">The repository includes the frontend, Express API, and Python service.</p></div><Link className="text-primary font-semibold text-sm underline underline-offset-4" href="https://github.com/salonipandey-dev/ResQPaws">View source on GitHub →</Link></div>
  </main><Footer /></>;
}
